### ISSUE TITLE
 LLM4Science Hackathon

### ISSUE THREAD

**Issue by Irratzo** [Helmholtz-AI-Matter/HAICON24-unconference#2]
# Title

**LLM4Science Hackathon**

_Connected issues: [Satellite events issue](https://github.com/FZJ-INM1-BDA/HAICon2024-satellite-events/issues/5), [unconference issue](https://github.com/Helmholtz-AI-Matter/HAICON24-unconference/issues/2). Deprecate whichever has been ruled out._

# Description

A hackathon where researchers can play around with language models (LLMs), apply them to their data of choice, integrate them with their services of interest, etc. Here are some examples of similar hackathons and their outcomes. [1](https://doi.org/10.1039/D3DD00113J), [2](https://www.catalyzex.com/paper/arxiv:2306.06283/code), [3](https://www.cecam.org/workshop-details/1291). Here are some possibly relevant Helmholtz resources. [Blablador](https://helmholtz-blablador.fz-juelich.de/), [OpenGTP-X](https://opengpt-x.de/en/). Other maybe useful material: [karpathy](https://github.com/karpathy/nn-zero-to-hero), [ethz-llm24](https://rycolab.io/classes/llm-s24/).

# Organizational

The organization would be found in discussion in this issue thread.

## Host(s)

| Name | Role | School | Affiliation | Contacts |
| ------ | ---- | ------- | ---------- | -------- |
| Johannes Wasmer | TBD | HDSLEE | [FZJ PGI-1](https://go.fzj.de/pgi-1) | @Irratzo, j dot wasmer at fz-juelich.de, [workplace profile](https://go.fzj.de/wasmer) |

More hosts would be found in discussion in this issue thread.

## Format

The format would be found in discussion in this issue thread.

## Timeframe

The timeframe and duration would be found in discussion in this issue thread.

One point to determine is whether to do this event at the satellite events on June 11 in Jülich (longer) or at the unconference June 12 morning (shorter). See "connected issues" above.

## Number of participants

TBD

## Material

Required materials would be found in discussion in this issue thread.

**Comment by helenehoffmann** [comment]
Dear Johannes,
is it already decided whether this will be part of the satellite day?

**Comment by Irratzo** [comment]
This issue has been deprecated in favor of the connected [Satellite events issue](https://github.com/FZJ-INM1-BDA/HAICon2024-satellite-events/issues/5).
