### ISSUE TITLE
3D Reconstruction on Augmented Reality

### ISSUE THREAD

**Issue by eyildiz-ugoe** [Helmholtz-AI-Matter/HAICON24-unconference#7]
# Title
3D Reconstruction on Augmented Reality

# Description

AR technology is rapidly developing. AR glasses are going to be every day mobile devices very soon. This will inevitably create an AR App industry that uses visual input and output. Topics like 3D reconstruction, 6D pose estimation are likely to be talked in the context of Augmented Reality. 

A simple example would be to complete a partially available scene with the 3D models that are available. This requires AR devices and a computation server to be in touch, exchanging information. Ideally, an image with an incomplete object (e.g. Colosseum) could be completed in augmented reality once its 3D model is fit into the scene. Doing this would complete the scene for a user as a part of an immersive experience. Depending on the 3D model quality, the user could even browse the inner parts of the scene. Users could go back in time, visualising the original form of ancient buildings and structures.

Sample use cases:

- Seeing partially ruined buildings completely (e.g. seeing the Colosseum as it was in the past)
- Working with an unknown object, having access to its sub-parts (e.g. automotive engine -> cylinder) and having a better understanding of the whole.
- Teaching the students concepts in-depth (e.g. human body -> lungs -> bronchioles) understanding the mechanisms better.

Questions to be addressed: 

- What are the delicate points in building a pipeline that could fetch and fit 3D models into an augmented reality? 
- What are some areas where this product could gain popularity? Where do you think the first area should be for trials? (e.g. tourism, industry, education)

Task to be solved:  

- 6D pose estimation
- 3D model fitting
- Scene understanding

Final outcome or product: 

- AR application with scene understanding, 3D reconstruction and 6D pose estimation.

# Organizational

FZJ/IAS-8

## Host(s)

Erenus Yildiz e.yildiz@fz-juelich.de

## Format

Open discussion. Addressing possible challenges (e.g. 3D model scarcity) and how to go around them.

## Timeframe
1h

## Number of participants
3-10

## Material

- Projector
- Whiteboard

**Comment by helenehoffmann** [comment]
@eyildiz-ugoe 
Thank you so much for hosting a session at this Unconference! Your participation is what makes this event truly special.
Please, be prepared to give a 1-minute pitch for your topic to share at the beginning of the Unconference.

We’re excited to see you there and can’t wait for an amazing event!
Best,
The Organizing Team

**Comment by SusanneWenzel** [comment]
Dear @eyildiz-ugoe ,

many thanks for your contribution! We hope your session was successful and constructive!
 
To make this not only a nice experience during the conference but a sustainable format, we would like to release a short result on the Helmholtz AI Website. Please provide us with a little report about the discussion in your session:

- One or two intro sentences about the topic and the respective format of your session 
- What was most controversial, or about what did all participants agree on?
- What were the key ideas?
- Do you see any follow up on this discussion?

Depending on the intensity of the session it can be shorter (1/3 page) or longer (one pager).
 
Please post your report here by end of next week. Ina already confirmed to release that at a HAICON24 subpage at Helmholtz.ai.
 
Best regards,
@helenehoffmann and Susanne

**Comment by SusanneWenzel** [comment]
Dear @eyildiz-ugoe , Its a while ago now. Can you still provide a short report please !? ☝️

**Comment by eyildiz-ugoe** [comment]
Dear @SusanneWenzel, I don't think it applies to me, because my session slot was taken by someone else by the time I arrived. Since I did not want to intervene and cut his presentation off, I kinda gave up on my slot and let him finish his. Perhaps,  next time.
